---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8.3

inputs:
  - name: dp-frontend-renderer
    path: go/src/github.com/ONSdigital/dp-frontend-renderer

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-frontend-renderer/ci/scripts/build.sh
