---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.9

inputs:
  - name: dp-frontend-renderer

outputs:
  - name: build

run:
  path: dp-frontend-renderer/ci/scripts/build.sh
